//! `trs report`: turn a local diagnostic into something a maintainer can act
//! on, without the reporter having to think about what is in it.
//!
//! Both reports are built from the machine of whoever runs them, so both can
//! carry home paths, internal hostnames and command lines. That is the whole
//! design problem here: the payload is useful precisely because it is real.
//!
//! Three rules follow from it, and they are why this is a command rather than
//! two lines in the docs:
//!
//! 1. Redact what is mechanically detectable (credential shapes via
//!    `tracker::redact_secrets`, the home directory rewritten to `~`).
//! 2. Print the entire payload first. Redaction catches token shapes; it
//!    cannot know that `ssh prod-db-01` names your infrastructure. A human
//!    reading the actual bytes is the real safety net.
//! 3. Never post without being asked twice: `--submit` plus a `y` at the
//!    prompt. The default writes a file and tells you the command.

use std::io::{self, BufRead, Write};
use std::path::PathBuf;
use std::process::Command;

const REPO: &str = "dPeluChe/trs";

/// Rewrite the home directory to `~` and mask credential shapes.
///
/// Deliberately not exhaustive, and the caller is told so: an internal
/// hostname or a client's project name is not a pattern anything can detect.
pub(crate) fn scrub(text: &str) -> String {
    let masked = crate::tracker::redact_secrets(text);
    match std::env::var("HOME") {
        Ok(home) if !home.is_empty() => masked.replace(&home, "~"),
        _ => masked,
    }
}

fn confirm(prompt: &str) -> bool {
    print!("{} [y/N] ", prompt);
    let _ = io::stdout().flush();
    let mut line = String::new();
    match io::stdin().lock().read_line(&mut line) {
        Ok(_) => matches!(line.trim(), "y" | "Y" | "yes"),
        Err(_) => false,
    }
}

fn gh_available() -> bool {
    Command::new("gh")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Write `body` to `path`, or to a temp file when no path was given.
fn write_payload(body: &str, output: Option<&str>, default_name: &str) -> Option<PathBuf> {
    let path = output
        .map(PathBuf::from)
        .unwrap_or_else(|| std::env::temp_dir().join(default_name));
    match std::fs::write(&path, body) {
        Ok(()) => Some(path),
        Err(e) => {
            eprintln!("  could not write {}: {}", path.display(), e);
            None
        }
    }
}

fn finish(title: &str, path: Option<PathBuf>, submit: bool) {
    let Some(path) = path else { return };
    println!("\n  saved to {}", path.display());

    if !submit {
        println!("\n  nothing was sent. To open the issue yourself:");
        println!(
            "    gh issue create --repo {} --title '{}' --body-file {}",
            REPO,
            title,
            path.display()
        );
        return;
    }
    if !gh_available() {
        println!("\n  `gh` is not installed, so the issue was not opened.");
        println!("  Install it, or paste the file at https://github.com/{REPO}/issues/new");
        return;
    }
    if !confirm("\n  Open a PUBLIC issue with exactly the text above?") {
        println!("  not sent.");
        return;
    }
    let out = Command::new("gh")
        .args(["issue", "create", "--repo", REPO, "--title", title])
        .arg("--body-file")
        .arg(&path)
        .output();
    match out {
        Ok(o) if o.status.success() => {
            print!("  {}", String::from_utf8_lossy(&o.stdout));
        }
        Ok(o) => eprintln!("  gh failed: {}", String::from_utf8_lossy(&o.stderr).trim()),
        Err(e) => eprintln!("  could not run gh: {}", e),
    }
}

/// Parser-coverage report: which commands trs sees a lot of and compresses
/// badly. This is the input a parser request needs.
pub(crate) fn run_coverage(days: Option<u64>, output: Option<&str>, submit: bool) {
    let entries = crate::tracker::read_history();
    if entries.is_empty() {
        eprintln!("no history yet. Use trs for a few days, then run this again.");
        return;
    }
    let Some(json) = crate::router::handlers::stats_coverage::coverage_json_for(
        &entries,
        15,
        days.unwrap_or(30),
    ) else {
        eprintln!("no history in that window. Try a wider --days.");
        return;
    };
    let body = format!(
        "## Parser coverage\n\n\
         Generated by `trs report coverage` on trs {}.\n\n\
         Home paths are rewritten to `~` and credential shapes are masked. \
         Command samples are real, so read them before trusting this.\n\n\
         ```json\n{}\n```\n",
        env!("CARGO_PKG_VERSION"),
        scrub(json.trim())
    );
    println!("{}", body);
    println!("  ---");
    println!("  That is the whole payload. `sample` lines are real command");
    println!("  lines off this machine: internal hostnames and project names");
    println!("  are not something redaction can detect.");
    finish(
        "parser-coverage report",
        write_payload(&body, output, "trs-coverage.md"),
        submit,
    );
}

/// Bug report: version, platform, doctor results and recent history, in the
/// shape a maintainer can read without a round trip.
pub(crate) fn run_bug(summary: Option<&str>, output: Option<&str>, submit: bool) {
    let info = crate::debug_info::build_report();
    let body = format!(
        "## What happened\n\n{}\n\n\
         ## Environment\n\n\
         Generated by `trs report bug`. Home paths are rewritten to `~` and \
         credential shapes are masked; tee-log excerpts are real command \
         output, so read them before trusting this.\n\n\
         ```\n{}\n```\n",
        summary.unwrap_or("_Describe what you expected and what happened instead._"),
        scrub(info.trim())
    );
    println!("{}", body);
    println!("  ---");
    println!("  That is the whole payload, including recent command output.");
    finish(
        "bug report",
        write_payload(&body, output, "trs-bug.md"),
        submit,
    );
}

#[cfg(test)]
#[path = "report_tests.rs"]
mod tests;
